# Generated by Django 3.1.4 on 2020-12-09 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201209_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(to='todo.Category'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
