# Generated by Django 3.1.4 on 2020-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201209_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(choices=[('1', 'SUPER URGENT'), ('2', 'IMPORTANT'), ('3', 'ASAP'), ('4', 'CAN WAIT'), ('5', 'WHEN POSSIBLE')], max_length=50),
        ),
    ]
