# Generated by Django 3.1.4 on 2020-12-09 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201209_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='urgency',
            field=models.CharField(choices=[('1', 'SUPER URGENT'), ('2', 'IMPORTANT'), ('3', 'ASAP'), ('4', 'CAN WAIT'), ('5', 'WHEN POSSIBLE')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
